version: "3" 
services:
  jenkins: 
    image: 'jenkins/jenkins:latest'
    ports: 
    - '8082:8080'
    - '50000:50000'
    volumes: 
    - '~/unit-test-sample/jenkins:/var/jenkins_home'
    - '/var/run/docker.sock:/var/run/docker.sock'
    - '/usr/local/bin/docker:/usr/bin/docker'
  