version: "3" 
services:
  jenkins: 
    image: 'diegotomfurtado/devops-nodejs:latest'
    ports: 
    - '8082:8080'
    - '50000:50000'
    volumes: 
    - '/var/run/docker.sock:/var/run/docker.sock'
    - '/usr/local/bin/docker:/usr/bin/docker'
    - /sys:/sys
    privileged: true
  